services:
  - type: web
    name: expense-tracker-backend
    env: docker
    plan: free
    region: frankfurt

    buildCommand: >
      npm install &&
      npx prisma generate &&
      npx prisma migrate deploy

    startCommand: "node server.js"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    plan: free
    region: frankfurt
    databaseType: mysql
